[package]
name = "registry"
version = "0.3.0"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "registry"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang = "0.11.1"
anchor-spl = "0.11.1"
lockup = { path = "../lockup", features = ["cpi"] }
solana-program = "1.7.4"
